config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  resources :reminder_types do 
    resources :reminders
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reminders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  enum status: [:active, :archieved, :expired]
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    validates :title, :content, :expire_at, :status, :reminder_type_id,presence: true
    validates :status, inclusion: { in: %w(active archieved expired),message: "%{value} is not valid"}
    belongs_to :reminder_type
end

app/models/reminder_type.rb
class ReminderType < ApplicationRecord
    has_many :reminders
    validates :name,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #This is the change Iam making in the controller
end

app/controllers/reminder_types_controller.rb
class ReminderTypesController < ApplicationController
  before_action :set_reminder_type, only: [:edit, :update, :destroy]
  def index
    @reminder_types=ReminderType.all
  end
  def create
    @reminder_type=ReminderType.new(reminder_type_params)
    if @reminder_type.save
      flash[:notice]="Saved successfully"
      redirect_to reminder_types_path
    else
      render "new"
    end
  end
  def update
    if @reminder_type.update(reminder_type_params)
      redirect_to reminder_types_path, notice: "Updated successfully"
    else
      render "edit"
    end
  end
  def show
    @reminder_type = ReminderType.find(params[:id])
  end
  def edit
    @reminder_type = ReminderType.find(params[:id])
        render :edit
  end
  def new
    @reminder_type=ReminderType.new
  end
  def destroy
    @reminder_type = ReminderType.find(params[:id])
      if @reminder_type.destroy
        flash[:notice] = "Reminder type has been deleted successfully"
        redirect_to reminder_types_url
      else
        flash[:notice] = "Reminder type deletion failed"
      end
  end
  private
    def reminder_type_params
      params.require(:reminder_type).permit(:name)
    end
    def set_reminder_type
      @reminder_type=ReminderType.find params[:id]
    end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder,except: [:index,:new,:create]
  def index
    @reminders=Reminder.includes(:reminder_type).all
    @today_reminders=Reminder.where(expire_at: Time.now.beginning_of_day..Time.now.end_of_day)
    @tomorrow_reminders=Reminder.where(expire_at: Date.today+1.day)
    @this_month_reminders=Reminder.where(expire_at: Date.today..Date.today+30.days)
  end
  def new
    @reminder=Reminder.new
  end
  def edit
    @reminder = Reminder.find(params[:id])
    render :edit
  end
  def create
    @reminder=Reminder.new(reminder_params)
    if @reminder.save
      redirect_to reminders_path, notice: "Saved successfully"
    else
      render "new"
    end
  end
  def update
    if @reminder.update(reminder_params)
      redirect_to reminders_path, notice: "Updated successfully"
    else
      render "edit", notice: "Update not successfull"
    end
  end
  def destroy
    @reminder = Reminder.find(params[:id])
        if @reminder.destroy
            flash[:notice] = "Reminder type has been deleted successfully"
            redirect_to reminders_url
        else
            flash[:notice] = "Reminder type deletion failed"
        end
  end
  def show
    @reminder = Reminder.find(params[:id])
  end
  def search
    @reminders = Reminder.where("title like ?","%"+params[:title]+"%")
  end
  private
    def reminder_params
      params.require(:reminder).permit(:title,:content,:expire_at,:status,:reminder_type_id)
    end
    def set_reminder
      @reminder=Reminder.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminder_types_helper.rb
module ReminderTypesHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/common/_alert.html.erb
<div class="alert alert alert-dismissible fade show" role="alert">
  <strong><%= title %></strong><%= content %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/common/_error_message.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Error</h4>
  <% error_messages.each do |message| %>
    <p><%= message %></p> 
    <hr>
  <% end %>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <li class="nav-item <%= 'active' if controller_name == 'reminders' %>">
         <a class="nav-link active" aria-current="page" href="<%=reminders_path %>">Reminders</a>
       </li>
        <li class="nav-item">
          <a class= "nav-link active <%= 'active' if controller_name == 'reminder_types' %>" aria-current="page" href="<%=reminder_types_path %>">Reminder Types</a>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        -->
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'common/navbar' %>
  <div class="container">
  <% if notice %>
    <%=render "common/alert", alert_type: "Success", title: "Success", content: notice %>
  <% end %>
  <% if alert %>
    <%=render "common/alert", alert_type: "Caution", title: "Error", content: alert %>
  <% end %>
  <%= yield %>
  </div>
  </body>
</html>

app/views/reminder_types/_form.html.erb
<%= form_for @reminder_type do |f| %>
  <% if reminder_type.errors.any? %>
    <%= render "common/error_message",object: reminder_type %>
  <% end %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%=f.text_field :name, class: "form-control",placeholder: "Enter name", required: true %>
    <br>
  </div>
  <div class="mb-3">
      <%= f.submit "Submit",class: "btn-success" %>
  </div>
<% end %>

app/views/reminder_types/edit.html.erb
<h1>Edit Reminder Types</h1>
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
    </div>
    <div class="col col-lg-6">
      <%= render "form",reminder_type: @reminder_type %>
    </div>
    <div class="col col-lg-4">
    </div>
  </div>
</div>

app/views/reminder_types/index.html.erb
<h1>ReminderTypes</h1>
<%= link_to "New", new_reminder_type_path %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">S.no</th>
      <th scope="col">No of Remainders</th>
      <th scope="col">Name</th>
      <th scope="col">Reminders</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @reminder_types.each do |reminder_type| %>
      <tr>
        <th scope="row"><%=reminder_type.id %></th>
        <td><%= reminder_type.name %></td>
        <td><%= reminder_type.reminders.count %></td>
        <td><%= link_to "Reminders", reminder_type_reminders_path(reminder_type) %></td>
        <td><%= link_to "Edit", edit_reminder_type_path(reminder_type) %><%= button_to "Delete", reminder_type_path(reminder_type),method: :delete,class: "btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reminder_types/new.html.erb
<h1>Create new Reminder Types</h1>
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
    </div>
    <div class="col col-lg-6">
      <%= render "form",reminder_type: @reminder_type %>
    </div>
    <div class="col col-lg-4">
    </div>
  </div>
</div>

app/views/reminder_types/show.html.erb
<h1>ReminderTypes#show</h1>
<p>Find me in app/views/reminder_types/show.html.erb</p>

app/views/reminders/_form.html.erb
<%= form_for @reminder do |f| %>
    <div class="mb-3">
      <label for="name" class="form-label">Title</label>
      <%=f.text_field :title, class: "form-control",placeholder: "Title", required: true %>
      <br>
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Content</label>
      <%=f.text_field :content, class: "form-control",placeholder: "Content", required: true %>
      <br>
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Remainder Type</label>
      <%= f.select :reminder_type_id,ReminderType.all.map{|rt| [rt.name,rt.id]},{prompt: "Select Remainder type"}, {class: "form-control",placeholder: "Content", required: true} %>
      <br>
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Expires at</label>
      <%=f.datetime_field :expire_at, class: "form-control",placeholder: "Expiry date", required: true %>
      <br>
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Status</label>
      <%=f.select :status,Reminder.statuses.map{|key,value| [key.titleize,key]},{prompt: "Select status"}, {class: "form-control",placeholder: "Select status", required: true} %>
      <br>
    </div>
    <div class="mb-3">
      <%= f.submit "Submit",class: "btn-success" %>
    </div>
  <% end %>

app/views/reminders/_reminders.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">S.no</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Remainder Types</th>
      <th scope="col">Expire at</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% reminders.each do |reminder| %>
      <tr>
        <th scope="row"><%=reminder.id %></th>
        <td><%= reminder.title %></td>
        <td><%= reminder.content %></td>
        <td><%= reminder.reminder_type %></td>
        <td><%= reminder.expire_at %></td>
        <td><%= reminder.status %></td>
        <td><%= link_to "Edit", edit_reminder_path(reminder),class: "btn-primary" %>
        <br>
        <td><%= button_to "Delete", reminder_path(reminder),method: :delete,class: "btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reminders/edit.html.erb
<h1>Edit Reminder</h1>
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
    </div>
    <div class="col col-lg-6">
      <%= render "form",reminder: @reminder %>
    </div>
    <div class="col col-lg-4">
    </div>
  </div>
</div>

app/views/reminders/index.html.erb
<h1>Reminders</h1>
<%= link_to "New", new_reminder_path %>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Today</button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Tomorrow</button>
    <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">This month</button>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
  <%= render "reminders", reminders: @today_reminders %> 
  </div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  <%= render "reminders", reminders: @tomorrow_reminders %> 
  </div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
  <%= render "reminders", reminders: @this_month_reminders %> 
  </div>
</div>

app/views/reminders/new.html.erb
<h1>Create new Reminder</h1>
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
    </div>
    <div class="col col-lg-6">
      <%= render "form",reminder: @reminder %>
    </div>
    <div class="col col-lg-4">
    </div>
  </div>
</div>

app/views/reminders/show.html.erb
<h1>Reminders#show</h1>
<p>Find me in app/views/reminders/show.html.erb</p>